<?php

namespace AppBundle\Repository;

/**
 * MeetupGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetupGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
