<?php

namespace AppBundle\Repository;

/**
 * MeetupEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetupEventRepository extends \Doctrine\ORM\EntityRepository
{
}
