imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
      handler_id: snc_redis.session.handler

    fragments: ~
    http_method_override: true
    assets:
      json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

    php_errors:
        log: true

    serializer: { enable_annotations: true }


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: %env(DATABASE_URL)%

  orm:
    default_entity_manager: ~
    auto_mapping: true
    mappings:
      AppBundle:
        type: annotation

# Swiftmailer Configuration
swiftmailer:

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: secured_area
    user_class: AppBundle\Entity\Security\User
    registration:
      confirmation:
        enabled: false

    from_email:
        address: "stadolf@gmail.com"
        sender_name: "Stefan"

snc_redis:
  clients:
    default:
      type: predis
      alias: session
      dsn: %env(REDIS_URL)%

  session:
    client: session
    prefix: sess

hwi_oauth:
  connect:
    account_connector: app_bundle.oauth_user_provider
  # list of names of the firewalls in which this bundle is active, this setting MUST be set
  firewall_names: [secured_area]
  resource_owners:
    github:
      type:          github
      client_id:     %env(GITHUB_CLIENT_ID)%
      client_secret: %env(GITHUB_CLIENT_SECRET)%
      scope:         'user:email,public_repo'
      options:
        csrf: true
      paths:
        identifier: login
        resource_owner_id: id

  fosub:
    username_iterations: 30
    properties:
      github: github_id