homepage:
  path: '/'
  defaults:
    _controller: FrameworkBundle:Template:template
    template:    '@App/homepage.html.twig'

app:
  resource: '@AppBundle/Controller/'
  type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_github_login:
    path: /login/check-github

logout:
    path: /logout