# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  _defaults:
    autowire: true

  DMS\Service\Meetup\MeetupKeyAuthClient:
    factory: ['DMS\Service\Meetup\MeetupKeyAuthClient', 'factory']
    arguments: [ {key: '%env(MEETUP_API_KEY)%'} ]

  AppBundle\Services\MeetupService: ~

  AppBundle\Repository\MeetupGroupRepository:
    factory: ['@doctrine', getRepository]
    arguments: ['AppBundle:MeetupGroup']

  AppBundle\Services\MercuryExcerptService:
    arguments: ['@guzzle', 'https://mercury.postlight.com',  '%env(MERCURY_API_KEY)%' ]


  app_bundle.oauth_user_provider:
    class:        AppBundle\Entity\Security\UserProvider
    arguments: ['@fos_user.user_manager', { github: github_id }]

  guzzle:
    class: GuzzleHttp\Client
    arguments:
      -
        timeout: 30
        allow_redirects: true
        handler: '@guzzle.stack'

  guzzle.stack:
    public: false
    class: GuzzleHttp\HandlerStack
    factory: [ GuzzleHttp\HandlerStack, create ]
    calls:
      - [ push, [ '@guzzle.logger' ] ]

  guzzle.message_formatter:
    public: false
    class: GuzzleHttp\MessageFormatter

  guzzle.logger:
    public: false
    class: callback
    arguments: ['@logger', '@guzzle.message_formatter']
    factory: [GuzzleHttp\Middleware, 'log']
